// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieList.Models;

#nullable disable

namespace MovieList.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230904224711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieList.Models.Genre", b =>
                {
                    b.Property<string>("GenreKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreKey");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreKey = "A",
                            Name = "Action"
                        },
                        new
                        {
                            GenreKey = "C",
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreKey = "D",
                            Name = "Drama"
                        },
                        new
                        {
                            GenreKey = "H",
                            Name = "Horror"
                        },
                        new
                        {
                            GenreKey = "M",
                            Name = "Musical"
                        },
                        new
                        {
                            GenreKey = "R",
                            Name = "RomCom"
                        },
                        new
                        {
                            GenreKey = "S",
                            Name = "SciFi"
                        });
                });

            modelBuilder.Entity("MovieList.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("GenreKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreKey");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 4,
                            GenreKey = "D",
                            Name = "Casablanca",
                            Rating = 5,
                            Year = 1942
                        },
                        new
                        {
                            MovieId = 2,
                            GenreKey = "A",
                            Name = "Wonder Woman",
                            Rating = 3,
                            Year = 2017
                        },
                        new
                        {
                            MovieId = 3,
                            GenreKey = "R",
                            Name = "Moonstruck",
                            Rating = 4,
                            Year = 1988
                        });
                });

            modelBuilder.Entity("MovieList.Models.Movie", b =>
                {
                    b.HasOne("MovieList.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieList.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
